### PR TITLE
Readme file with alternative OR example

### PR DESCRIPTION
**Pull request by 1nstinct**
I've made alternative or.js file, that provide ability to verfiy any count of policies. Please review them, and give me feedback :)

### CODE REVIEW

**Comment by mastilver** [comment]
@1nstinct Thank you for the PR
Could you use markdown instead of html
(Try to keep it one commit long by using `git commit --amend`)

**Comment by 1nstinct** [comment]
@mastilver Sorry, but it seemed to me, that I've faild with --amend

**Comment by mastilver** [comment]
Haha, I have no idea how you did that :D

lgtm, I will merge that tonight

**Comment by mastilver** [comment]
Completely forget that one...

**Pull request merged**
